musicplayer/music/urls.py
from django.conf.urls import  url
from . import views

app_name ='music'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<album_id>[0-9]+)/$',views.details,name='details'),
    url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorites,name='favorties'),

]

musicplayer/musicplayer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls')),
]

musicplayer/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length= 100)
    album_title=models.TextField(max_length=200)
    album_logo=models.CharField(max_length = 300)

    def __str__(self):
         return self.artist

class Song(models.Model):
    albu=models.ForeignKey(Album , on_delete=models.CASCADE)  
    file_type=models.CharField(max_length=200)
    song_title=models.CharField(max_length=200)  
    is_favorite = models.BooleanField(default= False)

    def __str__(self):
        return self.song_title

musicplayer/music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Album , Song
from django.template import loader
# Create your views here.

def index(request):
    all_albums = Album.objects.all()
     ### Without Template###
    # result = ""
    # for album in all_albums :
    #   result+=album.artist+" - "+album.album_title+"    "
    # return HttpResponse(result)

     ### With Template###
    template=loader.get_template('index.html')
    context = { 'all_albums' : all_albums  }
     # return HttpResponse(template.render(context,request))
    return render(request,'index.html',context)

def details(request,album_id):
      all_albums = Album.objects.all()
      album=all_albums.get(pk=album_id)
      context = {'album' : album}
      return render(request,'details.html',context)
    # return HttpResponse("The AlbumId is : "+ str(album_id))

def favorites(req,album_id):
    all_albums = Album.objects.all()
    album=all_albums.get(pk=album_id)
    try:
        selected_song =album.song_set.get(pk=req.POST['song'])
    except :
        return render(req ,'details.html', {'album' : album,
        'error_msg':'THere is no song with this id'})
    else:
        selected_song.is_favorite = True
        return render(req,'details.html',{'album':album})

musicplayer/music/templates/details.html
<img src="{{ album.album_logo }}">
{% if error_msg %}
    <p><strong> {{error_msg}}</strong></p>
{% endif %}

<h1>{{album.artist}}</h1>
<form action="{% url 'music:favorties' album.id %}" method="POST">
    {%csrf_token%}
    {% for song in album.song_set.all %}
    <input type="radio" id="{{forloop_counter}}" name="song" value="{{song.id}}"
    <label for ="song{{forloop_counter}}">
        {{song.song_title}} <br>
        {% if song.is_favorite %}
        <img src="https://clip2art.com/images/star-clipart-small-star-4.png" style="width:20%;height: 20%;">
        {% endif %}
    </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>
<h3>{{album.album_title}}</h3>
  

musicplayer/music/templates/index.html
{% if all_albums %}
  <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:details' album.id %}">{{album.album_title}} -{{album.artist}}</a></li>
        {% endfor %}
  </ul>
  {% else %}
        <h3>You dont have any list</h3>
  {% endif %}